# This file was auto-generated by Polybuild

ifndef OS
	OS := $(shell uname)
endif

obj_ext := .o
ifeq ($(OS),Windows_NT)
	obj_ext := .obj
	out_ext := .exe
endif

compiler := $(CXX)
compilation_flags := -Wall -O2
libraries :=

default: gtfo$(out_ext)
.PHONY: default

obj/main_0$(obj_ext): ./main.cpp
	@printf '\033[1m[POLYBUILD]\033[0m Compiling $@ from $<...\n'
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished compiling $@ from $<!\n'

gtfo$(out_ext): obj/main_0$(obj_ext)
	@printf '\033[1m[POLYBUILD]\033[0m Building $@...\n'
	@$(compiler) $^ $(static_libraries) $(compilation_flags) $(libraries) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished building $@!\n'

clean:
	@printf '\033[1m[POLYBUILD]\033[0m Deleting gtfo$(out_ext) and obj...\n'
	@rm -rf gtfo$(out_ext) obj
	@printf '\033[1m[POLYBUILD]\033[0m Finished deleting gtfo$(out_ext) and obj!\n'
.PHONY: clean

install:
	@printf '\033[1m[POLYBUILD]\033[0m Copying gtfo$(out_ext) to /usr/local/bin...\n'
	@cp gtfo$(out_ext) /usr/local/bin
	@printf '\033[1m[POLYBUILD]\033[0m Finished copying gtfo to /usr/local/bin!\n'
.PHONY: install
